# Generated by Django 3.2.5 on 2021-07-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blank_app', '0002_auto_20210714_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankcontent',
            name='new_blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankcontent', to='blank_app.newblank'),
        ),
    ]
