# Generated by Django 3.2.5 on 2021-07-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank_app', '0003_alter_blankcontent_new_blank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newblank',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
